server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/
      suffix: .html
logging:
  level:
    root: info
  path: C:\WindowsD\log
####自定义的配置
custom:
  config:
    ignores:
      get:
        - /toLogin
        - /403
      post:
        - /login
        - /logout
      pattern:
        - /static/**