server:
  port: 8082
spring:
  mvc:
    static-path-pattern: /templates/**
    view:
      prefix: /templates/
      suffix: .html
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000ms
logging:
  level:
    root: info
  path: C:\WindowsD\log


