{{- $fullName := .Release.Name -}}
{{- $chartName := .Chart.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $chartName }}-secret
type: Opaque
data:
{{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
