{{- $fullName := .Release.Name -}}
{{- $chartName := .Chart.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $chartName }}-service
  labels:
    name: {{ $fullName }}-{{ $chartName }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $fullName }}-{{ $chartName }}

